### ISSUE TITLE
Please work on the overlap problem.

### ISSUE THREAD

**Issue by mandysimon88** [w8r/martinez#8] opened 2016-11-16 17:49 UTC
Here is a very simple test case:
polygon 1: [[0,7], [7,0], [14,0], [21,7]] (trapezoid
poylgon 2: [[0,3.5], [0,0], [21,0], [21,3.5]] (box overlapping top half of trapezoid)

both polygons have an edge at y = 0 and overlap between x = 7 and x = 14.

result: [[3.5,3.5],[7,0],[14,0]]... plus bad vertices: [21,0], [14,0], and [21, 3.5] and missing good vertex [17.5, 3.5].

We wrote workarounds to remove the bad vertices ('any vertex that is outside one or the other original shapes') but it's hard to figure out how to insert the missing one.

This seems to be the only flaw in your otherwise awesomely performant algorithm... would be awesome if this bug did not exist!

**Comment by mandysimon88** [comment] 2016-12-12 12:59
This example works on the 'fixes' branch now.

**Comment by w8r** [comment] 2016-12-12 13:22
Can I see the code please?

**Comment by mandysimon88** [comment] 2016-12-12 13:35
I just ran this and got identical results, on your `fixes` branch.
// Modified version of index.js. Run with `node index.js`

```
// module.exports = require('./src/index');
var martinez = require('./src/index');

var trapezoid = [
  [0,7],
  [7,0],
  [14,0],
  [21,7],
  [0,7]
]

var box = [
  [0,3.5],
  [0,0],
  [21,0],
  [21,3.5],
  [0,3.5]
]

var intersection = martinez.intersection(trapezoid, box)
console.log('Right: 3.5,3.5,7,0,14,0,17.5,3.5,3.5,3.5')
console.log('Actual:' + intersection)
```

logs come out the same

**Comment by mandysimon88** [comment] 2016-12-12 13:40
but the other examples aren't working... do you know when you'll have some time to work on this? it's okay if you don't. it would just be really helpful to our planning to have an idea.

**Comment by w8r** [comment] 2016-12-12 14:24
that's interesting. `fixes` contains unfinished work of conversion the library to use a different binary tree implementation, it's now mostly broken

As the matter of fact, I have just relocated to another country and have a lot to take care of, so my spare time is really limited, I cannot really tell for sure that I would be able to work on it this month.

**Comment by gap777** [comment] 2016-12-12 18:38
@w8r, can you provide any support to us as we endeavor to fix it?

**Comment by w8r** [comment] 2016-12-13 12:23
yes, absolutely!

**Comment by gap777** [comment] 2016-12-13 12:24
Great! Can you share your thoughts here on what you think the problem is caused by?

**Comment by w8r** [comment] 2016-12-13 12:30
1. You can uncomment the visual debug and try to follow the perpendicular line sweeping to see where it gets wrong. 
2. Also as I said the huge problem is the unstable tree structure which holds vertically sorted segments for finding the intersection.
3. If you are looking for a fast solution for simpler polygons you can try and remove all the occurrences of `contourId` from the code. It's a concept I added trying to lift off the limitation of the multipolygons and overlapping edges in the same polygon.

**Comment by ctechdevelopment** [comment] 2017-02-07 23:41
Did you guys have any luck on this issue? Happy to help if not ...

**Comment by gap777** [comment] 2017-02-08 02:11
Not yet fixed. We would love help on this.

**Comment by ctechdevelopment** [comment] 2017-02-08 03:38
@w8r did you use as reference the updated 2013 version of the martinez paper? I'm wondering if this is an algorithm or implementation issue - i'll have time to look at this if its the latter :)

**Comment by lyrachord** [comment] 2017-02-08 06:55
Should be, I guess.
And there is a link for cpp implementation and another binding(forget that great lib's name) on Professor Matinez's hompeage

**Comment by w8r** [comment] 2017-02-08 09:05
@ctechdevelopment it's an implementation problem, I would appreciate your help. I have listed the leads that I currently have in a comment above. I used the updated paper, yes. 
The only problem with the algorithm itself, as discussed with the author, are the polygons sharing multiple edges but they can be fixed. Basically, most of the problems stem from the data-structure and sorting in the vertical sweepline

**Comment by ctechdevelopment** [comment] 2017-02-08 16:32
Awesome, to simplify things, is there much (any) relevant differences between the two papers here, just finished reading 2008 and looks straight forward. And is the multi polygon stuff fully implemented?

**Comment by w8r** [comment] 2017-02-08 16:47
To be honest, I didn't compare them since I've get a hold of the new version pretty quickly. The paper may look straightforward, but it is not really detailed on the edge cases that are only covered in the provided C++ code.

For the multipolygon stuff is implemented by me and pretty naively, and I guess that's what's causing the problems as well. I am convinced that the cascading can be avoided there. There's a contour lookup hash, and a respective field in polygons to handle that. But it has to reflect in the `compareEvents` and `compareSegments` as well, and since I added those rules, in some cases the binary tree I was using was not able to retrieve the segments that I put there. 

Altogether that data structure is bad and the idea of using something ported from C++ so directly(iterators and so on) is flawed. The implementation of the binary tree is not at all critical for this algorithm since even in the really heavy data sets it is observed to contain no more than 20 segments at a time.

**Comment by ctechdevelopment** [comment] 2017-02-09 15:13
A quick update: haven't had too much time to look at this, however, I've quickly tested the sample data from @mandysimon88 with both implementations at https://github.com/akavel/martinez-src and they also returns incorrect results. I don't feel I have the time to do whats needed to get this working right now with other commitments. That being said I would like to return to this as there isn't currently an elegant solution for this (clipperjs, which is stable is also very convoluted).

I would suggest someone finding a good stable martinez implementation to run data comparisons with - at that stage I think it would be a more manageable task with limited time (as I'm sure you know, discovering "special cases" that are either not mentioned or not covered enough in computational geometry papers can be challenging and time consuming to debug :)

**Comment by w8r** [comment] 2017-02-09 15:25
> discovering "special cases" that are either not mentioned or not covered enough in computational geometry papers can be challenging and time consuming to debug

Haha you can feel my pain))) all the implementations known to me are abandoned even at an earlier stage than mine or are based on the older version of the paper. 

Anyway thanks for your support, I will soon get back to the algorithm since now I can see some timeslots coming

**Comment by ctechdevelopment** [comment] 2017-03-03 15:45
hey @w8r did you manage to find time to take a look at this yet?

**Comment by w8r** [comment] 2017-03-03 16:00
Yes, working on it. Thanks to @rowanwins I have an (almost) working sweepline (I am fixing tests in the branch now and will make a minor release), next thing would be to go through the kindly provided testcases and see what's wrong with them

**Comment by ctechdevelopment** [comment] 2017-03-03 17:05
legend! 👍

**Comment by ctechdevelopment** [comment] 2017-04-20 17:16
Have you seen https://github.com/voidqk/polybooljs ?

**Comment by DenisCarriere** [comment] 2017-04-20 18:08
> Have you seen https://github.com/voidqk/polybooljs ?

We've already tested `polybooljs` and it has very similar issues/struggles as `martinez`, one is not better than the other.

**Comment by ctechdevelopment** [comment] 2017-04-21 00:27
Ahhh ok - they are both so close to being very robust!

**Comment by rowanwins** [comment] 2017-04-21 00:28
@ctechdevelopment we're currently working on a number of fixes so fingers crossed we're getting close!

**Comment by gap777** [comment] 2017-05-26 20:27
It seems like fixes have been merged to master... are these issues closed? When are you going to make a new release?

**Closed** 2017-05-28 21:16 UTC
